var digitalData = {
    versionDL: "1.10",
    pageInstanceID: "de",
    page: {
        pageInfo: {
            pageName: "",
            pageIntent: "transaccion",
            pageSegment: "general",
            sysEnv: "escritorio",
            version: "",
            channel: "online",
            language: "ES",
            geoRegion: "",
            level1: "",
            level2: "",
            level3: "",
            level4: "",
            level5: "",
            level6: "",
            level7: "",
            level8: "",
            level9: "",
            level10: "",
            area: "publica",
            server: "window.location.hostname",
            bussinessUnit: "BBVA Frances",
            errorPage: "",
        },
        pageActivity: {
            search: {
                onSiteSearchResults: "",
                onSiteSearchTerm: "",
                originalPage: "",
            },
            nameOfVideoDisplayed: "",
        },
    },
    internalCampaign: {
    	attributes : [{
            location: "",
            campaignFormat: "",
            collectiveCode: "",
            campaignName: "",
            product: "",
            productCode: "",
            quantity: "",
    	}],
    	event : {
        eventInfo: {
            eventName: "",
            siteActionName: "",
            }
        },
    },
    user: {
        device: {
            userAgent: "",
            mobile: "no",
        },
        userState: "no logado",
        profileID: "",
        segment: {
            global: "",
            profile: "",
        },
        gender: "",
        country: "",
        state: "",
        age: "",
    },
    application: {
        transactionID: "",
        application: {
            type: "",
            name: "",
        },
        fulfillmentModel: "",
        amount: "",
        paymentAmount: "",
        numberOfPayments: "",
        paymentDate: "",
        paymentType: "",
        serviceCharge: "",
        typology: "",
        currency: "",
        programTypeHired: "",
        offer: "",
        operationNumber: "",
        term: "",
        interestRate: "",
        process: "",
        step: "",
        interactionLevel: "",
        state: "",
        errorType: "",
    },
    product: {
        primaryCategory: "",
        productSubtype: "",
        productName: "",
    },
};